:toc:
:toclevels: 1
:toc-title: Contents
:icons: font
:idprefix:
:jbake-status: published
:encoding: utf-8
:lang: en-US
:sectanchors: true
:sectlinks: true
:linkattrs: true
= JniJarBinary
:jbake-type: dsl_chapter
:jbake-tags: user manual, gradle plugin dsl, JniJarBinary
:jbake-description: Learn about the build language of the JniJarBinary type.

API Documentation: link:../javadoc/dev/nokee/platform/jni/JniJarBinary.html[JniJarBinary]

Configuration for a Java Native Interface (JNI) JAR binary.
A JNI JAR refers to a JAR binary containing only the shared library binary.
It's only present if the library generate multiple variants.
If the JNI library has only a single variant, the shared library binary is included inside the link:../javadoc/dev/nokee/platform/jni/JvmJarBinary.html[JvmJarBinary].

The binaries are accessible via the library's link:../javadoc/dev/nokee/platform/base/BinaryView.html[BinaryView] containing all the binary instance of a library:


[.listing]
----

plugins {
    id 'dev.nokee.jni-library'
    id 'dev.nokee.cpp-language'
    id 'java'
}

import dev.nokee.platform.jni.JniJarBinary

library {
    binaries.withType(JniJarBinary).configureEach {
        // ...
    }
}

----


The binary of a specific variant is also accessible via the variant's link:../javadoc/dev/nokee/platform/base/BinaryView.html[BinaryView]:


[.listing]
----

plugins {
    id 'dev.nokee.jni-library'
    id 'dev.nokee.cpp-language'
    id 'java'
}

import dev.nokee.platform.jni.JniJarBinary

library {
    variants.configureEach {
        binaries.withType(JniJarBinary).configureEach {
            // ...
        }
    }
}

----


== Properties



[cols="1,2", options="header", width=100%]
|===
|Property
|Description


|link:#dev.nokee.platform.jni.JniJarBinary:jarTask[jarTask]
|The Jar task for this binary.

|===




== Methods

No methods.




== Property Details


[[dev.nokee.platform.jni.JniJarBinary:jarTask]]
=== link:https://docs.gradle.org/6.2.1/javadoc/org/gradle/api/tasks/TaskProvider.html[TaskProvider]<link:https://docs.gradle.org/6.2.1/javadoc/org/gradle/jvm/tasks/Jar.html[Jar]> jarTask (read-only)

The link:https://docs.gradle.org/6.2.1/javadoc/org/gradle/jvm/tasks/Jar.html[Jar] task for this binary.









