:toc:
:toclevels: 1
:toc-title: Contents
:icons: font
:idprefix:
:jbake-status: published
:encoding: utf-8
:lang: en-US
:sectanchors: true
:sectlinks: true
:linkattrs: true
= JvmJarBinary
:jbake-type: dsl_chapter
:jbake-tags: user manual, gradle plugin dsl, JvmJarBinary
:jbake-description: Learn about the build language of the JvmJarBinary type.

API Documentation: link:../javadoc/dev/nokee/platform/jni/JvmJarBinary.html[JvmJarBinary]

Configuration for a JVM JAR binary.
A JVM JAR refers to a JAR binary containing only the compiled classes.
It is always present and the instance is shared across all variants.
If the JNI library has only a single variant, the produced JAR will also contain theshared library binary.

The binary is accessible via the library's link:../javadoc/dev/nokee/platform/base/BinaryView.html[BinaryView] containing all the binary instance of a library:


[.listing]
----

plugins {
    id 'dev.nokee.jni-library'
    id 'dev.nokee.cpp-language'
    id 'java'
}

import dev.nokee.platform.jni.JvmJarBinary

library {
    binaries.withType(JvmJarBinary).configureEach {
        // ...
    }
}

----


The binary is also accessible via the variant's link:../javadoc/dev/nokee/platform/base/BinaryView.html[BinaryView] containing only the binaries instance for a specific variant:


[.listing]
----

plugins {
    id 'dev.nokee.jni-library'
    id 'dev.nokee.cpp-language'
    id 'java'
}

import dev.nokee.platform.jni.JvmJarBinary

library {
    variants.configureEach {
        binaries.withType(JvmJarBinary).configureEach {
            // ...
        }
    }
}

----


== Properties



[cols="1,2", options="header", width=100%]
|===
|Property
|Description


|link:#dev.nokee.platform.jni.JvmJarBinary:jarTask[jarTask]
|The Jar task for this binary.

|===




== Methods

No methods.




== Property Details


[[dev.nokee.platform.jni.JvmJarBinary:jarTask]]
=== link:https://docs.gradle.org/6.2.1/javadoc/org/gradle/api/tasks/TaskProvider.html[TaskProvider]<link:https://docs.gradle.org/6.2.1/javadoc/org/gradle/jvm/tasks/Jar.html[Jar]> jarTask (read-only)

The link:https://docs.gradle.org/6.2.1/javadoc/org/gradle/jvm/tasks/Jar.html[Jar] task for this binary.









